//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public int ComplainID { get; set; }
        public int UserID { get; set; }
        public string ComplainType { get; set; }
        public string ComplainDescription { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
