//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int TrainID { get; set; }
        public int RouteID { get; set; }
        public string RouteSource { get; set; }
        public string RouteDestination { get; set; }
        public double TotalDistance { get; set; }
        public int NumberOfStations { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
