//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int CoachID { get; set; }
        public int ID { get; set; }
        public int TrainID { get; set; }
        public int SeatNumber { get; set; }
        public int BirthNumber { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Train Train { get; set; }
    }
}
