//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public int CustomerID { get; set; }
        public string SrcStation { get; set; }
        public string DstStation { get; set; }
        public int Fare { get; set; }
        public Nullable<int> AllocatedSeat { get; set; }
        public Nullable<int> AllocatedBirth { get; set; }
        public int TrainID { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Train Train { get; set; }
    }
}
